{% set name = "qp" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LSSTDESC/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 30cc2a96aa11cca8d4b18cfb7416d6151da23c133d3d878a1835d0fe127fc668

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm <=6.1.0
    - setuptools_scm_git_archive

  run:
    - python >=3.6
    - numpy
    - scipy >=1.7.0
    - matplotlib-base
    - scikit-learn
    - tables-io >=0.7.4
    - deprecated

test:
  imports:
    - qp

about:
  home: http://github.com/LSSTDESC/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quantile parametrization for probability distribution functions.
  description: |
    A python package for handling probability distributions using various parametrizations
  dev_url: https://github.com/LSSTDESC/{{ name }}

extra:
  recipe-maintainers:
    - eacharles
